
<html>
<head>
    <meta http-equiv=Content-Type content="text/html;charset=utf-8">
    <link rel="stylesheet" href="theme/css/wechat.css" type="text/css" charset="utf-8">
</head>
<body>
  <p>当需要重新抛出 Python 的异常时，很多人都处理不好。本文总结了一些处理方法。</p>
<pre class="codehilite"><code class="language-python">try:
    do_something()
except:
    do_cleanup()</code></pre>


<p>这种处理会直接把内部异常吃掉，当有问题/Bug时，会很难处理，所以不推荐。</p>
<pre class="codehilite"><code>try:
    do_something()
except Exception as e:
    do_cleanup()
    print e
    # or
    import traceback
    traceback.print_exc()</code></pre>


<p>这种直接打印的，一是不能很好的输出到日志里。二是不能把错误交到上层调用者，不能让其知道这是有问题。</p>
<pre class="codehilite"><code>try:
    do_somethink()
except:
    do_cleanup()
    raise</code></pre>


<p>用这种，主要是为了做cleanup。直接<code>raise</code>后，异常会抛向上层。没有catch的效果一样。</p>
<p>这里还有一种和上面这个类似的效果的</p>
<pre class="codehilite"><code>try:
    do_something()
except:
    import sys
    exc_info = sys.exc_info()
    raise exc_info[0], exc_info[1], exc_info[2]</code></pre>


<p>最后，当要抛出自己重新包装后的异常时，最好把原始的异常也带上。这样有利于问题的debug。</p>
<pre class="codehilite"><code>try:
    do_something()
except:
    import sys
    exc_info = sys.exc_info()
    raise MyException(), None, exc_info[2]</code></pre>


<h1 id="ref">REF</h1>
<ul>
<li><a href="http://www.ianbicking.org/blog/2007/09/re-raising-exceptions.html">Re-raising Exceptions</a> - by Ian Bicking</li>
</ul>
</body>
</html>
